### ISSUE TITLE
Some issues about test cases generated by EvoMaster

### ISSUE THREAD

**Issue by qixin5** [EMResearch/EMB#10]
Dear EvoMaster authors,

I would like to bring to your attention some issues I saw for the test cases generated by EvoMaster for features-service. For this API, when I ran some of the test cases generated by EvoMaster, I found that some methods (e.g., addRequiresConstraintToProduct) are not exercised. Then I made some changes to the test case code, and the issues were resolved.

Please see the changes I made for the files attached. Without making these changes, the method addRequiresConstraintToProduct (in class ProductsConstraintsResource) is not exercised by EvoMasterTest0.java, and the method addExcludesConstraintToProduct (also in class ProductsConstraintsResource) is not exercised by EvoMasterTest1.java.

[test_cases.tar.gz](https://github.com/EMResearch/EMB/files/5681480/test_cases.tar.gz)

**Comment by arcuri82** [comment]
thanks for your interest in EM.

EM does not guarantee 100% coverage, as it is a heuristic-based randomized algorithm. Furthermore, it also all depends on how long you let it run (we recommend between 1 and 24 hours). 

In previous experiments, on features-service we usually achieve around 73% coverage. Of course, more needs to be done (eg, better heuristics) to push that number even higher (eg 80% / 90%)
