### ISSUE TITLE
Is there a way to obtain the swagger specifications of the applications within the EMB?

### ISSUE THREAD

**Issue by chrisbartoloburlo** [EMResearch/EMB#49]
Following the recent [publication](https://arxiv.org/pdf/2205.05325.pdf) in which a group of API fuzzers were tested I was wondering from where one could obtain the Swagger specifications of the applications upon which the fuzzers were tested on. It would be of great help if a link to these sources was provided. Thanks!

**Comment by arcuri82** [comment]
Hi,
  thanks for your interest. Each API has an endpoint from where you can download the schemas at runtime (see the driver classes for the URLs). However, indeed it would be useful to have them directly on file in the rep. We ll add them. 
Meanwhile, you can access some (most?) of them here in this other rep [https://github.com/EMResearch/EvoMaster/tree/master/core/src/test/resources/swagger/sut](https://github.com/EMResearch/EvoMaster/tree/master/core/src/test/resources/swagger/sut)

**Comment by chrisbartoloburlo** [comment]
Thanks for the link, very helpful! 
Is it on purpose that the responses within the files only contain information about the response code and not the body?

**Comment by arcuri82** [comment]
Hi. no idea... we haven't modified those files, they are as they are...

**Comment by arcuri82** [comment]
a new folder called `openapi-swagger` has now been added, including all schemas for the RESTful APIs. currently under `develop` branch, till next release where it ll be merged into `master`
