### ISSUE TITLE
Could not transfer artifact org.evomaster:evomaster-client-database-spy:jar:1.0.1-SNAPSHOT from/to jcenter (http://jcenter.bintray.com/): Access denied to: http://jcenter.bintray.com/org/evomaster/evomaster-client-database-spy/1.0.1-SNAPSHOT/evomaster-client-database-spy-1.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by xz8090** [EMResearch/EMB#9]
The following error occurred when I imported the EMB project：
Could not transfer artifact org.evomaster:evomaster-client-database-spy:jar:1.0.1-SNAPSHOT from/to jcenter (http://jcenter.bintray.com/): Access denied to: http://jcenter.bintray.com/org/evomaster/evomaster-client-database-spy/1.0.1-SNAPSHOT/evomaster-client-database-spy-1.0.1-SNAPSHOT.jar
How to solve it？

**Comment by arcuri82** [comment]
Hi,
 this issue was supposed to be covered in the [readme](https://github.com/EMResearch/EMB).
I added some clarifications to it. See section `Build The Projects`.

Let me know if that is still not clear enough

**Comment by xz8090** [comment]
![image](https://user-images.githubusercontent.com/25838582/75613799-c8b32280-5b6c-11ea-96bd-e727e6b4dbcd.png)

**Comment by xz8090** [comment]
Hi,
EvoMaster BUILD SUCCESS, but EMB BUILD FAILURE.

[INFO] ---------------< org.javiermf.features:features-service >---------------
[INFO] Building features-service 1.0.1-SNAPSHOT                          [1/46]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.evomaster:evomaster-client-database-spy:jar:1.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] features-service 1.0.1-SNAPSHOT .................... FAILURE [  2.041 s]
[INFO] scout-api 1.0-SNAPSHOT ............................. SKIPPED
[INFO] data-access 1.0-SNAPSHOT ........................... SKIPPED
[INFO] auth 1.0-SNAPSHOT .................................. SKIPPED
[INFO] data-batch-jobs 1.0-SNAPSHOT ....................... SKIPPED
[INFO] api 1.0-SNAPSHOT ................................... SKIPPED
[INFO] ProxyPrint-kitchen 1.0-SNAPSHOT .................... SKIPPED
[INFO] org.zalando:catwatch 0.0.1-SNAPSHOT ................ SKIPPED
[INFO] catwatch-backend 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] EvoMaster Benchmark (EMB) 1.0.1 .................... SKIPPED
[INFO] evomaster-benchmark-cs 1.0.1 ....................... SKIPPED
[INFO] evomaster-benchmark-cs-rest 1.0.1 .................. SKIPPED
[INFO] evomaster-benchmark-cs-rest-original 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial 1.0.1 ....... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-ncs 1.0.1 ... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-scs 1.0.1 ... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-news 1.0.1 .. SKIPPED
[INFO] OCVN 1.3.0-SNAPSHOT ................................ SKIPPED
[INFO] OCVN Persistence 1.3.0-SNAPSHOT .................... SKIPPED
[INFO] OCVN MongoDB Persistence 1.3.0-SNAPSHOT ............ SKIPPED
[INFO] OCVN Web 1.3.0-SNAPSHOT ............................ SKIPPED
[INFO] OCVN UI 1.3.0-SNAPSHOT ............................. SKIPPED
[INFO] OCVN Forms 1.3.0-SNAPSHOT .......................... SKIPPED
[INFO] evomaster-benchmark-cs-rest-gui 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em 1.0.1 ....................... SKIPPED
[INFO] evomaster-benchmark-em-external 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em-external-rest 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-features-service 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-scout-api 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-proxyprint 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ncs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-scs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-catwalk 1.0.1 . SKIPPED
[INFO] evomaster-benchmark-em-external-rest-news 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ind0 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ocvn 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-embedded 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-features-service 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-scout-api 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-proxyprint 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-ncs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-scs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-catwatch 1.0.1  SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-news 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-ocvn 1.0.1 .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.783 s
[INFO] Finished at: 2020-03-01T20:03:39+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project features-service: Could not resolve dependencies for project org.javiermf.features:features-service:jar:1.0.
1-SNAPSHOT: Could not find artifact org.evomaster:evomaster-client-database-spy:jar:1.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by xz8090** [comment]
Oh, I success. Thank you!
java -jar evomaster.jar --outputFolder F:\Idea\EMB-1.0.0\em\external\rest\features-service\src\evo --maxTimeInSeconds 10
* [34m
 _____          ___  ___          _
|  ___|         |  \/  |         | |
| |____   _____ | .  . | __ _ ___| |_ ___ _ __
|  __\ \ / / _ \| |\/| |/ _` / __| __/ _ \ '__|
| |___\ V / (_) | |  | | (_| \__ \ ||  __/ |
\____/ \_/ \___/\_|  |_/\__,_|___/\__\___|_|

                    [0m
* EvoMaster version: 1.0.0
* There are 18 usable RESTful API endpoints defined in the schema configuration
* Starting to generate test cases

[1A[2K* Consumed search budget: 15.390%; covered targets: 0; time per test: 1514.0ms (1.0 actions)
[1A[2K* Consumed search budget: 21.360%; covered targets: 82; time per test: 685.7ms (1.0 actions)
[1A[2K* Consumed search budget: 26.760%; covered targets: 118; time per test: 505.4ms (1.0 actions)
[1A[2K* Consumed search budget: 32.260%; covered targets: 165; time per test: 278.5ms (1.0 actions)
[1A[2K* Consumed search budget: 37.540%; covered targets: 227; time per test: 210.9ms (1.0 actions)
[1A[2K* Consumed search budget: 53.850%; covered targets: 243; time per test: 225.6ms (1.0 actions)
[1A[2K* Consumed search budget: 63.660%; covered targets: 270; time per test: 218.4ms (1.0 actions)
[1A[2K* Consumed search budget: 69.760%; covered targets: 270; time per test: 206.6ms (1.0 actions)
[1A[2K* Consumed search budget: 74.870%; covered targets: 270; time per test: 188.0ms (1.0 actions)
[1A[2K* Consumed search budget: 84.250%; covered targets: 270; time per test: 187.5ms (1.0 actions)
[1A[2K* Consumed search budget: 89.760%; covered targets: 270; time per test: 181.8ms (1.0 actions)
[1A[2K* Consumed search budget: 95.070%; covered targets: 270; time per test: 145.7ms (1.0 actions)
[1A[2K* Consumed search budget: 100.310%; covered targets: 270; time per test: 134.7ms (1.0 actions)
* Going to save 19 tests to F:\Idea\EMB-1.0.0\em\external\rest\features-service\src\evo
* Evaluated tests: 59
* Evaluated actions: 59
* Needed budget: 100%
* Passed time (seconds): 11
* Covered targets (lines, branches, faults, etc.): 270
* Potential faults: 13
* Bytecode line coverage: 26% (112 out of 426 in 33 units/classes)
* [32mTo obtain better results, use the '--maxTime' option to run the search for longer[0m
* EvoMaster process has completed successfully
* Use [32m--help[0m and visit [34mhttp://www.evomaster.org[0m to learn more about available options

**Comment by arcuri82** [comment]
Hi,
  glad to hear you got it to work.
You originally wrote: `Could not find artifact org.evomaster:evomaster-client-database-spy:jar:1.0.1-SNAPSHOT`. Does it mean that you first built EvoMaster without `mvn install`?
Or was there any other problem which you now fixed?
I d like to know, so I can update the docs accordingly... :)

**Comment by xz8090** [comment]
I had successfully build EvoMaster, but I failed to build EMB with `mvn install` because my `maven` downloads some `jar` files are often interrupted. I modified the maven download source and waited more than 4 hours to get it all down.

**Comment by arcuri82** [comment]
thanks for the clarification.
it looks like a general networking problem on your side, and not something specific to EvoMaster. i ll close this issue then
